// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhpnechiwtgfcbafzmaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxocG5lY2hpd3RnZmNiYWZ6bWFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDIyNzUsImV4cCI6MjA2NTgxODI3NX0.Ie6h7eTTODiolL0NHYPXKLFGS5GAIKNIH82bV4b3lMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);